# Generated by Django 4.2.9 on 2026-02-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='available',
            field=models.BooleanField(default=True, help_text='Token availability status'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expiration_time',
            field=models.IntegerField(default=10, help_text='Token expiration time in minutes'),
        ),
    ]
