# Generated by Django 4.2.9 on 2026-02-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0002_emailverification_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_uuid', models.CharField(max_length=255)),
                ('point_id', models.CharField(max_length=255)),
                ('point_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'robot_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
